banan updates (armbian)

diff --git a/banan/customs/usr/local/bin/mountall b/banan/customs/usr/local/bin/mountall
--- a/banan/customs/usr/local/bin/mountall
+++ b/banan/customs/usr/local/bin/mountall
@@ -1,11 +1,21 @@
-#!/bin/sh
+#!/bin/sh -x
 
 
 
-LABEL=WD_ELEMENTS
+#LABEL=WD_ELEMENTS
+#DEV="/dev/disk/by-label/$LABEL"
+
+#pmount -u 022 -w -A -t ntfs-3g -c utf8 "$DEV" "${LABEL}.OLD" || echo failed
+
+
+
+LABEL=WD_E_2000GB
 DEV="/dev/disk/by-label/$LABEL"
+pmount -u 022 -w -A -t ntfs-3g -c utf8 "$DEV" "$LABEL" || echo failed
 
-pmount -u 022 -w -A -t ntfs-3g -c utf8 "$DEV" "$LABEL" || exit 1
 
+sudo cryptsetup luksOpen /dev/disk/by-partuuid/dbd2dbef-4de4-470f-8722-843a1005a0b0 oe || exit 4
+
+sudo mount /dev/mapper/oe /media/oe || exit5
 
 #sudo hdparm -B 1  "$DEV" || exit 2
